name: docker
on:
  workflow_dispatch: {}
  release:
    types:
      - published

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  docker:
    name: build-publish
    uses: leukosaima/gh-actions/.github/workflows/docker-github-builder.yaml@25da0c94eadf6e17128d671111e0b8665feb40a6 # main
    secrets: inherit
