name: pr

on:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  dotnet:
    uses: leukosaima/gh-actions/.github/workflows/dotnet-build.yaml@25da0c94eadf6e17128d671111e0b8665feb40a6 # main
    with:
      target: ntfyrr.sln
      dotnet-version: 10.0.x
      configuration: Release
