name: pr

on:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  dotnet:
    uses: leukosaima/gh-actions/.github/workflows/dotnet-build.yaml@4e681293c007e0872330b2cbce53a4ddbe4a30d7 # main
    with:
      target: ntfyrr.sln
      dotnet-version: 10.0.x
      configuration: Release
