name: pr

on:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  dotnet:
    uses: leukosaima/gh-actions/.github/workflows/dotnet-build.yaml@b0f5a3400d38b6bade95b12c04b69abd770a972f # main
    with:
      target: ntfyrr.sln
      dotnet-version: 10.0.x
      configuration: Release
